### ISSUE TITLE
Logshark ResourceManager plugin fails when run against Tableau Server 10.4 logs

### ISSUE THREAD

**Issue by KALYANRENGANATHAN** [tableau/Logshark#28]
Hello

I have installed Logshark 2.0 and when i try pull server log to visualize it it is throwing following error

2017-10-25 01:16:33,469 wsjcit1043566_17102508145683_srmlogszip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Encountered uncaught exception while executing plugin 'ResourceManager': No total memory limit found for { "_id" : "worker2/vizqlserver/Logs/backgrounder_2-1_2017_10_25_00_44_38.txt-572", "ts" : ISODate("2017-10-25T00:44:43.424Z"), "pid" : 601136, "tid" : "93f9c", "sev" : "info", "k" : "msg", "v" : "Resource Manager: listening on port 2233", "file_path" : "worker2\\vizqlserver\\Logs", "file" : "backgrounder_2-1_2017_10_25_00_44_38.txt", "worker" : 2, "line" : 572 }
2017-10-25 01:16:33,471 wsjcit1043566_17102508145683_srmlogszip (null) [1] DEBUG Logshark.Core.Controller.Plugin.PluginExecutor - <log4net.Error>Exception during StringFormat: Input string was not in a correct format. <format>System.Exception: No total memory limit found for { "_id" : "worker2/vizqlserver/Logs/backgrounder_2-1_2017_10_25_00_44_38.txt-572", "ts" : ISODate("2017-10-25T00:44:43.424Z"), "pid" : 601136, "tid" : "93f9c", "sev" : "info", "k" : "msg", "v" : "Resource Manager: listening on port 2233", "file_path" : "worker2\\vizqlserver\\Logs", "file" : "backgrounder_2-1_2017_10_25_00_44_38.txt", "worker" : 2, "line" : 572 }
   at Logshark.Plugins.ResourceManager.Helpers.MongoQueryHelper.GetTotalMemoryLimit(BsonDocument srmStartEvent, IMongoCollection`1 collection)
   at Logshark.Plugins.ResourceManager.Helpers.MongoQueryHelper.GetThreshold(BsonDocument srmStartEvent, IMongoCollection`1 collection)
   at Logshark.Plugins.ResourceManager.ResourceManager.PersistThresholds(Int32 workerId, IMongoCollection`1 collection)
   at Logshark.Plugins.ResourceManager.ResourceManager.ProcessSrmEvents()
   at Logshark.Plugins.ResourceManager.ResourceManager.Execute(IPluginRequest pluginRequest)
   at Logshark.Core.Controller.Plugin.PluginExecutor.ExecutePlugin(Type pluginType)</format><args>{}</args></log4net.Error>
2017-10-25 01:16:33,481 wsjcit1043566_17102508145683_srmlogszip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - ResourceManager failed to execute successfully.
2017-10-25 01:16:33,482 wsjcit1043566_17102508145683_srmlogszip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Initializing SearchServer plugin..
2017-10-25 01:16:33,484 wsjcit1043566_17102508145683_srmlogszip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Execution of SearchServer plugin started at 1:16 AM..
[Logshark.log.txt](https://github.com/tableau/Logshark/files/1416377/Logshark.log.txt)

**Comment by jmangue** [comment]
Hi @KALYANRENGANATHAN,

This is a compatibility bug with the ResourceManager plugin when run against 10.4 logsets.  Can you please verify that your logset is from Tableau Server 10.4?

Assuming this is the same bug, we already have an internal fix done for this and will release it to GitHub soon.

Thanks,
-Justin

**Comment by KALYANRENGANATHAN** [comment]
Justin

Your absolutely right I am using 10.4 pre release build and trying to
analyze logs using Logshark

Please let me know once it is available in Github

Thanks
Kalyan

**Comment by jmangue** [comment]
@KALYANRENGANATHAN thanks for confirming!

This bug should only affect the ResourceManager plugin, so in the meantime you should still be able to analyze your logs using the other ~11 plugins.

Thanks for your patience, I'll update this issue once a fix is out.

**Comment by til-jmac** [comment]
Hi there, any news on a fix for this? Now that 10.4 is out I'm trying to use the ResourceManager plugin in the wild and I keep getting this error. Thanks.

**Comment by jmangue** [comment]
Hi all, we are still working on a release date for the next version of Logshark, which will include this fix. Thanks for your patience.

**Comment by darrelranf** [comment]
Hi jmangue,

It appears I'm having a similar problem. I'm new to logshark and until seeing this post I haven't made much headway. Can you provide me the current status on this issue. 

I'm post a partial of the logshark.log so if you can, can you tell me if this is related to the bug you've discussed here? Thank you!

2018-01-11 16:44:48,710 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.ConnectionModel.Postgres.PostgresConnectionInfo - Created Postgres database 'exto-43vwzf2_18011121441585_log01032018zip' on 'localhost:5432'.
2018-01-11 16:44:48,731 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Initializing Apache plugin..
2018-01-11 16:44:48,734 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Execution of Apache plugin started at 4:44 PM..
2018-01-11 16:45:30,754 exto-43vwzf2_18011121441585_log01032018zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Encountered uncaught exception while executing plugin 'Apache': The operation has timed out.
2018-01-11 16:45:31,977 exto-43vwzf2_18011121441585_log01032018zip (null) [1] DEBUG Logshark.Core.Controller.Plugin.PluginExecutor - System.TimeoutException: The operation has timed out.
   at Npgsql.NpgsqlConnector.<Authenticate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at ServiceStack.OrmLite.OrmLiteConnection.Open()
   at ServiceStack.OrmLite.OrmLiteConnectionFactory.OpenDbConnection()
   at Logshark.PluginLib.Persistence.ConcurrentBatchPersister`1..ctor(IDbConnectionFactory connectionFactory, Int32 poolSize, Int32 maxBatchSize, IDictionary`2 recordsPersisted)
   at Logshark.PluginLib.Model.Impl.BasePlugin.GetConcurrentBatchPersister[T](IPluginRequest request)
   at Logshark.Plugins.Apache.Apache.Execute(IPluginRequest pluginRequest)
   at Logshark.Core.Controller.Plugin.PluginExecutor.ExecutePlugin(Type pluginType)
2018-01-11 16:45:31,979 exto-43vwzf2_18011121441585_log01032018zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Apache failed to execute successfully.
2018-01-11 16:45:31,980 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Initializing Backgrounder plugin..
2018-01-11 16:45:31,984 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Execution of Backgrounder plugin started at 4:45 PM..
2018-01-11 17:00:34,941 exto-43vwzf2_18011121441585_log01032018zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Encountered uncaught exception while executing plugin 'Backgrounder': The operation has timed out.
2018-01-11 17:02:03,011 exto-43vwzf2_18011121441585_log01032018zip (null) [1] DEBUG Logshark.Core.Controller.Plugin.PluginExecutor - System.TimeoutException: The operation has timed out.
   at Npgsql.NpgsqlConnector.<Authenticate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at ServiceStack.OrmLite.OrmLiteConnection.Open()
   at ServiceStack.OrmLite.OrmLiteConnectionFactory.OpenDbConnection()
   at Logshark.PluginLib.Persistence.ConcurrentCustomPersister`1..ctor(IPluginRequest pluginRequest, IDbConnectionFactory connectionFactory, InsertionMethod customInsertionMethod, IDictionary`2 recordsPersisted)
   at Logshark.Plugins.Backgrounder.Backgrounder.Execute(IPluginRequest pluginRequest)
   at Logshark.Core.Controller.Plugin.PluginExecutor.ExecutePlugin(Type pluginType)
2018-01-11 17:02:03,011 exto-43vwzf2_18011121441585_log01032018zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Backgrounder failed to execute successfully.
2018-01-11 17:02:50,957 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Initializing ClusterController plugin..
2018-01-11 17:03:34,098 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Execution of ClusterController plugin started at 5:03 PM..
2018-01-11 17:04:25,971 exto-43vwzf2_18011121441585_log01032018zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Encountered uncaught exception while executing plugin 'ClusterController': No such host is known
2018-01-11 17:10:51,312 exto-43vwzf2_18011121441585_log01032018zip (null) [1] DEBUG Logshark.Core.Controller.Plugin.PluginExecutor - System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at ServiceStack.OrmLite.OrmLiteConnection.Open()
   at ServiceStack.OrmLite.OrmLiteConnectionFactory.OpenDbConnection()
   at Logshark.PluginLib.Persistence.ConcurrentBatchPersister`1..ctor(IDbConnectionFactory connectionFactory, Int32 poolSize, Int32 maxBatchSize, IDictionary`2 recordsPersisted)
   at Logshark.PluginLib.Model.Impl.BasePlugin.GetConcurrentBatchPersister[T](IPluginRequest request)
   at Logshark.Plugins.ClusterController.ClusterController.Execute(IPluginRequest pluginRequest)
   at Logshark.Core.Controller.Plugin.PluginExecutor.ExecutePlugin(Type pluginType)
2018-01-11 17:10:51,312 exto-43vwzf2_18011121441585_log01032018zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - ClusterController failed to execute successfully.
2018-01-11 17:10:52,157 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Initializing Config plugin..
2018-01-11 17:10:59,284 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Execution of Config plugin started at 5:10 PM..
2018-01-11 17:11:44,574 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Skipped saving Config workbook because the plugin did not generate any backing data.
2018-01-11 17:11:44,575 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Config execution completed! [52.41]
2018-01-11 17:11:45,843 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Initializing Filestore plugin..
2018-01-11 17:11:54,579 exto-43vwzf2_18011121441585_log01032018zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Execution of Filestore plugin started at 5:11 PM..
2018-01-11 17:14:11,773 exto-43vwzf2_18011121441585_log01032018zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Encountered uncaught exception while executing plugin 'Filestore': No such host is known
2018-01-11 17:15:38,436 exto-43vwzf2_18011121441585_log01032018zip (null) [1] DEBUG Logshark.Core.Controller.Plugin.PluginExecutor - System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)

**Comment by jmangue** [comment]
Hi @darrelranf , your issue appears to be unrelated to the root ResourceManager issue here.

It looks like Logshark is timing out when trying to communicate with your Postgres database (running on localhost).  I'd recommend you start troubleshooting there; make sure you can connect to that database, issue queries, etc.

**Comment by sqlcenturion** [comment]
Hi all, 

Is there an update on when a patch will be released for the SRM issues?  We are now past the release of Tableau Server 10.5 and I am needed SRM info fairly badly.

Thanks!

**Comment by rahulmotwani** [comment]
Hi @sqlcenturion,

We are working on other higher priority deliverables as a team. We will determine the release date for the next version of Logshark in the near future, which will include this fix. Thank you for your patience, feedback and persistence.

**Comment by til-jmac** [comment]
It's now nearly 4 months since the last reply saying you would "determine the release date for the next version of Logshark in the near future", and 6 months since this bug was first identified. When can we expect a resolution here? Since the code is open source, are there some lines we can change to parse the Resource Manager logs correctly? Logshark has become quite a key tool for us, really looking forward to an updated version. Thank you.

**Comment by jmangue** [comment]
Hi all, we just released v2.1 which should resolve this issue with processing ResourceManager logs.  Please upgrade and feel free to open a new issue if you are still running into problems.
