### ISSUE TITLE
Error publishing to a SSL Tableau site

### ISSUE THREAD

**Issue by hieppo** [tableau/Logshark#54]
Error during publishing of the workbook (none of the workbook gets published).

If I have to publish a workbook using CLI TABADMIN, I have to use the --no-certcheck for it to publish.  I am assuming it has something to do with this particular workaround.

2018-09-07 15:18:11,295 se140323_18090719173330_se120017tablogbackup1zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Saved workbook to 'F:\Logshark\Output\se140323_18090719173330_se120017tablogbackup1zip\Config.twb'!
2018-09-07 15:18:11,306 se140323_18090719173330_se120017tablogbackup1zip (null) [1] INFO Logshark.Core.Controller.Workbook.WorkbookPublisher - Publishing 1 workbook to Tableau Server..
2018-09-07 15:18:11,464 se140323_18090719173330_se120017tablogbackup1zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Failed to publish workbooks: Unable to initialize Tableau Server for publishing: The underlying connection was closed: An unexpected error occurred on a receive.
2018-09-07 15:18:11,476 se140323_18090719173330_se120017tablogbackup1zip (null) [1] DEBUG Logshark.Core.Controller.Plugin.PluginExecutor - Logshark.Core.Exceptions.PublishingException: Unable to initialize Tableau Server for publishing: The underlying connection was closed: An unexpected error occurred on a receive. ---> Logshark.Core.Exceptions.PublishingException: Unable to initialize Tableau Server for publishing: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Tableau.RestApi.ApiRequest.ToHttpWebRequest()
   at Tableau.RestApi.ApiRequest.GetResponse(Int32 maxAttempts)
   at Tableau.RestApi.ApiRequest.IssueRequest(String requestFailureMessage, Int32 maxAttempts)
   at Tableau.RestApi.RestApiRequestor.Authenticate()
   at Tableau.RestApi.RestApiRequestor.GetAuthToken()
   at Tableau.RestApi.RestApiRequestor.GetSiteId()
   at Logshark.Core.Controller.Workbook.WorkbookPublisher.InitializeProject(IRestApiRequestor requestor)
   at Logshark.Core.Controller.Workbook.WorkbookPublisher.PublishWorkbooks(String pluginName, IEnumerable`1 workbooksToPublish)
   --- End of inner exception stack trace ---
   at Logshark.Core.Controller.Workbook.WorkbookPublisher.PublishWorkbooks(String pluginName, IEnumerable`1 workbooksToPublish)
   at Logshark.Core.Controller.Workbook.WorkbookPublisher.PublishWorkbooks(IPluginResponse pluginResponse)
   --- End of inner exception stack trace ---
   at Logshark.Core.Controller.Workbook.WorkbookPublisher.PublishWorkbooks(IPluginResponse pluginResponse)
   at Logshark.Core.Controller.Plugin.PluginExecutor.ExecutePlugin(Type pluginType, PluginExecutionRequest pluginExecutionRequest, IEnumerable`1 previousPluginResponses)
2018-09-07 15:18:11,478 se140323_18090719173330_se120017tablogbackup1zip (null) [1] ERROR Logshark.Core.Controller.Plugin.PluginExecutor - Config failed to execute successfully.
2018-09-07 15:18:11,478 se140323_18090719173330_se120017tablogbackup1zip (null) [1] INFO Logshark.Core.Controller.Plugin.PluginExecutor - Finished executing plugins! [1 failure]

**Comment by Xantrul** [comment]
First of all I would double-check that the problem is indeed with the cyphers/TLS version. Do to this, capture traffic on your local machine using WireShark (or similar tools) and then filter output by IP address of the Tableau Server and keep only ssl traffic (in WireShark filter simply called "ssl"). Then check "Client Hello" and related messages - they usually help to explain why secure connection cannot be established.

Earlier this week I had problems with .NET 4.6.1 and TLS v1.2 and 4.6 doesn't seem to always force TLS 1.2 as you noticed. The solution was to add this line to the Main method in Program.cs:
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
This global switch affects whole application

**Comment by hieppo** [comment]
Hi Xantrul,
You probably on to something.  I ran into this issue over on technet.  The OP has the exact same issue as what I am seeing.
https://social.technet.microsoft.com/Forums/en-US/a5835e0a-32da-4341-b676-b8cf31a13533/ssl-handshake-issue?forum=winserver8gen

It looks like the line of code need to be change in the source and recompile. I don't have the environment readily to do the compile since I am mainly support and need the install file.
Anyone able to make this change and push it down.

Thanks

**Comment by Xantrul** [comment]
I can't make any promises, but I'll try to include this line into the next release here

**Comment by Xantrul** [comment]
We enabled TLS v1.2 in version 3.0
